name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y libnotify4 libnotify-bin

      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: ./mvnw -B verify --file pom.xml

      - name: Test site generation
        run: ./mvnw -B site --file pom.xml
