name: Maven Release

on:
  release:
    types: [created]

permissions:
  contents: read
  pages: write
  packages: write
  id-token: write

concurrency:
  group: "publish"
  cancel-in-progress: false

jobs:
  build-and-publish:

    runs-on: ubuntu-latest      

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Setup Dependencies
      run: |
        sudo apt-get update 
        sudo apt-get install -y libnotify4 libnotify-bin
    
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        server-id: ossrh
        settings-path: ${{ github.workspace }}
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Build and publish to Apache Maven Central
      run: ./mvnw -s $GITHUB_WORKSPACE/settings.xml -B deploy -P release -Drevision=$GITHUB_REF_NAME -Dchangelist= --file pom.xml
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    
    - name: Site generation
      run: ./mvnw  -s $GITHUB_WORKSPACE/settings.xml -B site --file pom.xml -P release -Drevision=$GITHUB_REF_NAME -Dchangelist= --file pom.xml

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'target/site'
      
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
